namespace:
  create: false

global:
  imagePullPolicy: Never

postgres:
  flyway:
    baselineOnMigrate: false

ingress:
  host: pm.local
  tls:
    enabled: false           # lokalny dev na czystym HTTP, bez cert-manager
