namespace:
  name: pm-app
  create: true

global:
  imagePullPolicy: IfNotPresent

postgres:
  mode: cnpg
  image:
    repository: postgres
    tag: "16"
  storage: 2Gi
  storageClassName: standard
  credentialsSecret: postgres-credentials
  credentials:
    create: false
    user: pm
    database: pm
  flyway:
    baselineOnMigrate: false
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  cnpg:
    clusterName: pm-postgres
    instances: 3
    primaryUpdateStrategy: unsupervised
    imageName: ghcr.io/cloudnative-pg/postgresql:16
    storage: 2Gi
    storageClassName: standard
    parameters:
      maxConnections: "200"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    backup:
      enabled: false
      pluginName: barman-cloud.cloudnative-pg.io
      objectStoreName: pm-postgres-store
      schedule: "0 0 2 * * *"
      destinationPath: ""
      s3CredentialsSecret: pm-postgres-s3-credentials

backend:
  image:
    repository: pm-backend
    tag: "3.1-flyway"
  replicas: 2
  serverPort: 3000
  service:
    port: 3000
  hikari:
    maximumPoolSize: 5
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  roomTtl:
    lobbySeconds: 180
    inGameSeconds: 600

frontend:
  image:
    repository: pm-frontend
    tag: "1.0"
  replicas: 2
  service:
    port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

ingress:
  enabled: true
  className: nginx
  host: pm.local

redis:
  enabled: true
  image: redis:7-alpine
  host: redis
  port: 6379

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpu:
    enabled: true
    averageUtilization: 70
  memory:
    enabled: false
