apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: pm-app
data:
  SERVER_PORT: "3000"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-0.postgres.pm-app.svc.cluster.local:5432/pm"
