apiVersion: v1
kind: ServiceAccount
metadata:
  name: pm-backend
  namespace: pm-app
  labels:
    app: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pm-frontend
  namespace: pm-app
  labels:
    app: frontend
automountServiceAccountToken: false
