apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pm-operator
  namespace: pm-app
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "endpoints", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pm-operator-binding
  namespace: pm-app
subjects:
  - kind: User
    name: pm-operator
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pm-operator
  apiGroup: rbac.authorization.k8s.io
