apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: {{ include "pm.namespace" . }}
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.serverPort }}
