apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ include "pm.namespace" . }}
data:
  SERVER_PORT: {{ .Values.backend.serverPort | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-0.postgres.{{ include "pm.namespace" . }}.svc.cluster.local:5432/{{ .Values.postgres.credentials.database }}"
  {{- if .Values.redis.enabled }}
  SPRING_DATA_REDIS_HOST: {{ .Values.redis.host | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.redis.port | quote }}
  APP_ROOM_TTL_LOBBY_SECONDS: {{ .Values.backend.roomTtl.lobbySeconds | quote }}
  APP_ROOM_TTL_IN_GAME_SECONDS: {{ .Values.backend.roomTtl.inGameSeconds | quote }}
  {{- end }}
