apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: {{ include "pm.namespace" . }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 8080
