{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "pm.namespace" . }}
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      name: redis
{{- end }}
